---
title: "R Notebook"
output: html_notebook
---


```{r}
mtcars[,c(1,3)]
```


```{r}
plot(mtcars[,c(1,3)])
```

```{r}
plot(scale(mtcars[,c(1,3)]))
```
```{r}
my_data <- scale(my_data)
mtcars.pca <- prcomp(my_data, center = F, scale. = F)
summary(mtcars.pca)
```
```{r}
plot(mtcars.pca$x, main = 'after PCA')
```

```{r}
mtcars.pca$rotation
```

```{r}
# make a fake data matrix
data.matrix <- matrix(nrow = 100, ncol = 10)
colnames(data.matrix) <- c(
  paste('wt', 1:5, sep = ''),
  paste('ko', 1:5, sep = '')
)
rownames(data.matrix) <- paste('gene', 1:100, sep = '')
for (i in 1:100) {
  wt.values <- rpois(5, lambda = sample(x=10:100, size=1))
  ko.values <- rpois(5, lambda = sample(x=10:100, size=1))
  
  data.matrix[i,] <- c(wt.values, ko.values)
}
head(data.matrix)
dim(data.matrix)
```

```{r}
pca <- prcomp(t(data.matrix), scale = TRUE)
```

```{r}
plot(pca$x[,1], pca$x[,2],main = 'pca')
```

```{r}
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)

barplot(pca.var.per, main = 'Scree Plot', xlab = 'Principal Component', ylab = 'Percent Variation')
```

```{r}
library(ggplot2)
pca.data <- data.frame(Sample=rownames(pca$x),
                       X=pca$x[,1],
                       Y=pca$x[,2])
pca.data
```

```{r}
ggplot(data = pca.data, aes(x = X, y = Y, label = Sample)) +
  geom_text() +
  xlab(paste("PC1 - ", pca.var.per[1], "%", sep='')) +
  ylab(paste("PC2- ", pca.var.per[2], "%", sep='')) +
  theme_bw() +
  ggtitle("My PCA Graph")
```

```{r}
loading_scores <- pca$rotation[,1]
gene_scores <- abs(loading_scores)
gene_score_ranked <- sort(gene_scores, decreasing = TRUE)
top_10_genes <- names(gene_score_ranked[1:10])

top_10_genes
```

































